# Generated by Django 4.2 on 2023-04-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_code', models.CharField(default='', max_length=256)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_descr', models.TextField(default='')),
                ('product_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('product_quantity', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_date', models.DateTimeField(auto_now=True)),
                ('output_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'my_product',
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp2.productmodel')),
                ('inbound_quantity', models.IntegerField()),
            ],
            bases=('erp2.productmodel',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp2.productmodel')),
                ('inbound_quantity', models.IntegerField()),
            ],
            bases=('erp2.productmodel',),
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp2.productmodel')),
                ('Outbound_quantity', models.IntegerField()),
                ('Outbound_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('erp2.productmodel',),
        ),
        migrations.CreateModel(
            name='Product_adding',
            fields=[
                ('productmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp2.productmodel')),
                ('product_adding_quantity', models.IntegerField()),
                ('adding_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('erp2.productmodel',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp2.productmodel')),
            ],
        ),
    ]
