# Generated by Django 4.2 on 2023-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp2', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_descr',
            field=models.TextField(default=''),
        ),
    ]
